Update package pdf-tools-20190219.1955

diff --git a/elpa/pdf-tools-20190220.1835/build/server/autobuild b/elpa/pdf-tools-20190220.1835/build/server/autobuild
--- a/elpa/pdf-tools-20190220.1835/build/server/autobuild
+++ b/elpa/pdf-tools-20190220.1835/build/server/autobuild
@@ -30,6 +30,8 @@ DRY_RUN=
 INSTALL_DIR=
 # Whether we can install packages.
 OS_IS_HANDLED=true
+# Which OSs installer to use
+OS=
 
 ## +-----------------------------------------------------------+
 ## * Utility Functions
@@ -38,17 +40,19 @@ OS_IS_HANDLED=true
 usage()
 {
     cat <<EOF
-usage:$(basename "$0") [--help|-n|[-i DIR|-I]]
+usage:$(basename "$0") [--help|-n|-i DIR|[-d -D]|[--os OS]]
 
-    -n      Don't do anything, but check if this OS is handled.
+    -n       Don't do anything, but check if this OS is handled.
 
-    -i DIR  Install the program in the given directory.
+    -i DIR   Install the program in the given directory.
 
-    -d      Force dependency installattion.
+    -d       Force dependency installattion.
 
-    -D      Skip dependency installattion.
+    -D       Skip dependency installattion.
 
-    --help  Display this message.
+    --os OS  Use the given OS's installer
+
+    --help   Display this message.
 
 EOF
     exit "$1"
@@ -185,6 +189,11 @@ handle_options()
                 if [ "${1%%/}" != "${PWD%%/}" ]; then
                     INSTALL_DIR=$1
                 fi ;;
+            --os)
+                shift
+                [ $# -gt 0 ] || usage 1
+                OS="$1"
+                ;;
             *) usage 1 ;;
         esac
         shift
@@ -403,22 +412,45 @@ os_gentoo() {
     return 0
 }
 
+# By Parameter --os
+os_argument() {
+    [ -z "$OS" ] && return 0
+    case $OS in
+        macos)   os_macos   "$@";;   
+        freebsd) os_freebsd "$@";; 
+        arch)    os_arch    "$@";;    
+        centos)  os_centos  "$@";;  
+        openbsd) os_openbsd "$@";; 
+        fedora)  os_fedora  "$@";;  
+        debian)  os_debian  "$@";;  
+        gentoo)  os_gentoo  "$@";;  
+        msys2)   os_msys2   "$@";;   
+        nixos)   os_nixos   "$@";;
+        *)       echo "Invalid --os argument: $OS"
+                 exit 1
+    esac || {
+        echo "Unable to install on this system as $OS"
+        exit 1
+    }
+}
+
 ## +-----------------------------------------------------------+
 ## * Figure out were we are, install deps and build the program
 ## +-----------------------------------------------------------+
 
 handle_options "$@"
 
-os_macos   "$@" || \
-os_freebsd "$@" || \
-os_arch    "$@" || \
-os_centos  "$@" || \
-os_openbsd "$@" || \
-os_fedora  "$@" || \
-os_debian  "$@" || \
-os_gentoo  "$@" || \
-os_msys2   "$@" || \
-os_nixos   "$@" || \
+os_argument "$@" || \
+os_macos    "$@" || \
+os_freebsd  "$@" || \
+os_arch     "$@" || \
+os_centos   "$@" || \
+os_openbsd  "$@" || \
+os_fedora   "$@" || \
+os_debian   "$@" || \
+os_gentoo   "$@" || \
+os_msys2    "$@" || \
+os_nixos    "$@" || \
 {
     OS_IS_HANDLED=
     if [ -z "$DRY_RUN" ]; then
